--liquibase formatted sql

--changeset giampaolo:01-create-account-table
CREATE TABLE account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Use GENERATED BY DEFAULT AS IDENTITY for H2 auto-increment
    account_number VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    balance DECIMAL(19, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);
--rollback DROP TABLE account;