# src/main/resources/application.yml
# ...
spring:
  application:
    payment: user-service
  # ...
  datasource:
    url: jdbc:h2:mem:bankdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1800000

  # jpa:
  #   hibernate:
  #     ddl-auto: update
  #   database-platform: org.hibernate.dialect.H2Dialect
  #   show-sql: true
  # ... rest of your Kafka and other configurations
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer # THIS IS THE KEY LINE
    consumer:
      group-id: consumer-group-id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.trusted.packages: "com.bank.system.payment_service.dto.*" # Crucial for JSON deserialization