# src/main/resources/application.yml
# ...
spring:
  application:
    name: account-service
  # ...
  datasource:
    url: jdbc:h2:mem:bankdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1800000
  # You can remove or keep the jpa section. If you're explicitly using JDBC,
  # the jpa properties won't be used, but having them won't necessarily cause issues
  # unless you have conflicting JPA-specific beans.
  # For clarity, if you are truly only using JDBC, you could remove this:
  # jpa:
  #   hibernate:
  #     ddl-auto: update
  #   database-platform: org.hibernate.dialect.H2Dialect
  #   show-sql: true
  # ... rest of your Kafka and other configurations

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.sql # Path to your master changelog file
    enabled: true # Explicitly enable Liquibase (it's true by default if starter is present)


  databaseChangeLog:
    - include:
        file: db/changelog/changes/01-create-account-table.sql # Changed to .sql